version: '2'

services:
  mongodb:
    container_name: usermanager_mongodb
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - "./app/.env"
    volumes:
      - ./database/data/db:/data/db
    ports:
      - 27045:27017
  
  usermanager:
    container_name: usermanager_app
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - "./app/.env"
    depends_on:
      - mongodb
    ports:
      - 49863:3000